/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Cloud({ ...props }) {
  const { nodes, materials } = useGLTF('./models/cloud/model.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry}>
        <meshStandardMaterial
          {...materials['lambert2SG.001']}
          transparent
          opacity={0.5}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('./models/cloud/model.glb');
